{% set data = load_setup_py_data() %}
{% set version = "0.1" %}

package:
  name: pixy
  
  version: {{ version }}

source:
  #path: ../src
  url: https://github.com/ksamuk/pixy/archive/{{ version }}.tar.gz

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - scikit-allel
    - tqdm
    - python

test:
  commands:
    - pixy --help

about:
  home: https://github.com/ksamuk/pixy
  license: MIT
  license_family: MIT
  summary: 'Unbiased estimation of nucleotide diversity within and between populations'
  description: |
    pixy is a command-line tool for painlessly and correctly estimating 
    average nucleotide diversity within (π) and between (dxy) populations from a VCF. 
    In particular, pixy facilitates the use of VCFs containing invariant (AKA monomorphic) 
    sites, which are essential for the correct computation of π and dxy.
  dev_url: https://github.com/ksamuk/pixy
  doc_url: https://pixy.readthedocs.io/en/latest/
  doc_source_url: https://github.com/ksamuk/pixy/blob/master/README.md
